<?php

namespace Database\Seeders;

use App\Models\Tantangan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TantanganSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            // Challenge 1: Usia Kehamilan 1-3 Bulan (Trimester 1)
            [
                'fase_id' => 1,
                'activity' => 'Melakukan pemeriksaan kehamilan',
                'point' => 10,
                'tingkat_ekonomi' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 1,
                'activity' => 'Mengecek tanda bahaya kehamilan',
                'point' => 15,
                'tingkat_ekonomi' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 1,
                'activity' => 'Tidur selama 6-7 jam di malam hari, tidur siang 1-2 jam',
                'point' => 5,
                'tingkat_ekonomi' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 1,
                'activity' => 'Menghindari paparan rokok',
                'point' => 10,
                'tingkat_ekonomi' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 1,
                'activity' => 'Mengonsumsi tablet tambah darah',
                'point' => 10,
                'tingkat_ekonomi' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Challenge 2: Pemberian (MPASI)
            [
                'fase_id' => 2,
                'activity' => 'Mulai MPASI pada usia 6 bulan dengan makanan yang kaya gizi',
                'point' => 15,
                'tingkat_ekonomi' => 3,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 2,
                'activity' => 'Perkenalkan berbagai jenis makanan dengan tekstur lembut',
                'point' => 10,
                'tingkat_ekonomi' => 3,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 2,
                'activity' => 'Berikan sayur dan buah setiap hari untuk memenuhi kebutuhan gizi',
                'point' => 10,
                'tingkat_ekonomi' => 3,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Challenge 3: Makanan Bergizi
            [
                'fase_id' => 3,
                'activity' => 'Berikan makanan yang mengandung protein, karbohidrat, dan lemak',
                'point' => 10,
                'tingkat_ekonomi' => 3,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 3,
                'activity' => 'Pastikan anak mendapatkan sumber vitamin dan mineral yang cukup',
                'point' => 10,
                'tingkat_ekonomi' => 3,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 3,
                'activity' => 'Hindari memberikan makanan olahan dan cepat saji yang tinggi gula',
                'point' => 15,
                'tingkat_ekonomi' => 3,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Challenge 4: Pencegahan Stunting
            [
                'fase_id' => 4,
                'activity' => 'Pastikan anak mendapatkan asupan gizi yang cukup sejak dalam kandungan',
                'point' => 15,
                'tingkat_ekonomi' => 3,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 4,
                'activity' => 'Tingkatkan perkembangan gizi yang seimbang untuk anak di usia bayi/belita',
                'point' => 10,
                'tingkat_ekonomi' => 3,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 4,
                'activity' => 'Lakukan imunisasi lengkap untuk mendukung tumbuh kembang optimal',
                'point' => 15,
                'tingkat_ekonomi' => 3,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Challenge 5: Imunisasi Dasar
            [
                'fase_id' => 5,
                'activity' => 'Pastikan anak mendapatkan imunisasi dasar lengkap sesuai jadwal',
                'point' => 15,
                'tingkat_ekonomi' => 3,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 5,
                'activity' => 'Konsultasikan dengan tenaga medis jika anak mengalami efek setelah imunisasi',
                'point' => 10,
                'tingkat_ekonomi' => 3,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 5,
                'activity' => 'Jangan lupa mencatat jadwal imunisasi berikutnya agar tidak terlewat',
                'point' => 5,
                'tingkat_ekonomi' => 3,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tingkat Ekonomi 2
            [
                'fase_id' => 1,
                'activity' => 'Minum air rebusan daun bayam untuk tambahan zat besi',
                'point' => 10,
                'tingkat_ekonomi' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 1,
                'activity' => 'Istirahat minimal 7 jam per hari',
                'point' => 5,
                'tingkat_ekonomi' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 1,
                'activity' => 'Konsumsi kacang hijau sebagai camilan sehat',
                'point' => 10,
                'tingkat_ekonomi' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 1,
                'activity' => 'Jalan kaki ringan 15 menit setiap hari',
                'point' => 5,
                'tingkat_ekonomi' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Challenge 2: MPASI Bergizi (5 entri)
            [
                'fase_id' => 2,
                'activity' => 'Berikan pure ubi jalar untuk MPASI pertama',
                'point' => 10,
                'tingkat_ekonomi' => 2,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 2,
                'activity' => 'Tambahkan wortel parut pada MPASI',
                'point' => 10,
                'tingkat_ekonomi' => 2,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 2,
                'activity' => 'Gunakan nasi tim sederhana dengan kaldu ayam kampung',
                'point' => 15,
                'tingkat_ekonomi' => 2,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 2,
                'activity' => 'Sajikan pisang tumbuk sebagai camilan',
                'point' => 5,
                'tingkat_ekonomi' => 2,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 2,
                'activity' => 'Pastikan bayi makan 3 kali sehari',
                'point' => 10,
                'tingkat_ekonomi' => 2,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Challenge 3: Pola Makan Anak (3 entri)
            [
                'fase_id' => 3,
                'activity' => 'Sajikan nasi dengan lauk tempe goreng',
                'point' => 10,
                'tingkat_ekonomi' => 2,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 3,
                'activity' => 'Berikan sayur kolplay sebagai tambahan gizi',
                'point' => 5,
                'tingkat_ekonomi' => 2,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 3,
                'activity' => 'Hindari camilan manis dari pedagang kaki lima',
                'point' => 10,
                'tingkat_ekonomi' => 2,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Challenge 4: Kesehatan Lingkungan (2 entri)
            [
                'fase_id' => 4,
                'activity' => 'Bersihkan halaman rumah dari genangan air',
                'point' => 10,
                'tingkat_ekonomi' => 2,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 4,
                'activity' => 'Gunakan kelambu saat tidur untuk hindari nyamuk',
                'point' => 5,
                'tingkat_ekonomi' => 2,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Challenge 5: Imunisasi dan Monitoring (6 entri)
            [
                'fase_id' => 5,
                'activity' => 'Kunjungi puskesmas untuk imunisasi BCG',
                'point' => 10,
                'tingkat_ekonomi' => 2,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 5,
                'activity' => 'Catat jadwal imunisasi DPT di buku KIA',
                'point' => 5,
                'tingkat_ekonomi' => 2,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 5,
                'activity' => 'Pantau berat badan anak di posyandu',
                'point' => 10,
                'tingkat_ekonomi' => 2,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 5,
                'activity' => 'Berikan air hangat jika anak demam setelah imunisasi',
                'point' => 5,
                'tingkat_ekonomi' => 2,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 5,
                'activity' => 'Konsultasi ke bidan jika ada keluhan pasca-imunisasi',
                'point' => 10,
                'tingkat_ekonomi' => 2,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 5,
                'activity' => 'Pastikan imunisasi campak selesai sebelum usia 1 tahun',
                'point' => 15,
                'tingkat_ekonomi' => 2,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tingkat Ekonomi 1
            [
                'fase_id' => 1,
                'activity' => 'Konsultasi rutin ke dokter kandungan di klinik swasta',
                'point' => 15,
                'tingkat_ekonomi' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 1,
                'activity' => 'Konsumsi suplemen prenatal impor setiap hari',
                'point' => 10,
                'tingkat_ekonomi' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 1,
                'activity' => 'Ikut kelas yoga prenatal mingguan',
                'point' => 15,
                'tingkat_ekonomi' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 1,
                'activity' => 'Minum jus organik buah segar setiap pagi',
                'point' => 10,
                'tingkat_ekonomi' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Challenge 2: MPASI Bergizi (3 Fase)
            [
                'fase_id' => 2,
                'activity' => 'Sajikan MPASI dengan daging sapi organik dan quinoa',
                'point' => 15,
                'tingkat_ekonomi' => 1,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 2,
                'activity' => 'Tambahkan minyak zaitun extra virgin pada MPASI',
                'point' => 10,
                'tingkat_ekonomi' => 1,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 2,
                'activity' => 'Gunakan blender khusus bayi untuk tekstur halus',
                'point' => 5,
                'tingkat_ekonomi' => 1,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Challenge 3: Pola Makan Anak (5 Fase)
            [
                'fase_id' => 3,
                'activity' => 'Sajikan salmon panggang dengan brokoli kukus',
                'point' => 15,
                'tingkat_ekonomi' => 1,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 3,
                'activity' => 'Berikan smoothie buah dengan yogurt organik',
                'point' => 10,
                'tingkat_ekonomi' => 1,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 3,
                'activity' => 'Hindari makanan cepat saji dan olahan',
                'point' => 10,
                'tingkat_ekonomi' => 1,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 3,
                'activity' => 'Sediakan camilan kacang almond panggang',
                'point' => 5,
                'tingkat_ekonomi' => 1,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 3,
                'activity' => 'Konsultasi menu harian ke ahli gizi',
                'point' => 15,
                'tingkat_ekonomi' => 1,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Challenge 4: Kesehatan Lingkungan (2 Fase)
            [
                'fase_id' => 4,
                'activity' => 'Pasang penyaring udara di kamar anak',
                'point' => 15,
                'tingkat_ekonomi' => 1,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 4,
                'activity' => 'Gunakan sabun organik untuk mandi anak',
                'point' => 10,
                'tingkat_ekonomi' => 1,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Challenge 5: Imunisasi dan Monitoring (6 Fase)
            [
                'fase_id' => 5,
                'activity' => 'Pilih vaksin premium di klinik swasta',
                'point' => 15,
                'tingkat_ekonomi' => 1,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 5,
                'activity' => 'Gunakan aplikasi untuk catat jadwal imunisasi',
                'point' => 5,
                'tingkat_ekonomi' => 1,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 5,
                'activity' => 'Cek pertumbuhan anak ke dokter spesialis',
                'point' => 15,
                'tingkat_ekonomi' => 1,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 5,
                'activity' => 'Berikan suplemen vitamin D sesuai anjuran dokter',
                'point' => 10,
                'tingkat_ekonomi' => 1,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 5,
                'activity' => 'Sediakan mainan edukasi pasca-imunisasi',
                'point' => 5,
                'tingkat_ekonomi' => 1,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fase_id' => 5,
                'activity' => 'Lakukan cek darah rutin untuk pantau kesehatan anak',
                'point' => 15,
                'tingkat_ekonomi' => 1,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($data as $tantangan) {
            Tantangan::create($tantangan);
        }

        // Tantangan::factory(15)->create();
    }
}
